# Generated by Django 2.1.5 on 2019-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsale',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=19),
        ),
    ]
