# Generated by Django 2.1.5 on 2019-02-07 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_groupsale_total_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsale',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
