# Generated by Django 2.1.5 on 2019-02-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_groupsale_purchase_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsale',
            old_name='total_sale',
            new_name='total_price',
        ),
    ]
